import { describe, it, expect, afterAll } from 'vitest';
import { generatePDF } from '../src/tools/designer.mjs';
import fs from 'fs';
import path from 'path';

describe('PDF Generation', () => {
  const testFilename = 'test_document.pdf';
  const testPath = path.join(process.cwd(), 'downloads', testFilename);

  it('should generate a PDF from raw HTML', async () => {
    const args = {
      filename: testFilename,
      html_content: '<h1>Test Document</h1><p>This is a test PDF generated by Vitest.</p>',
      summary: 'Test PDF Summary',
    };

    const result = await generatePDF(args);

    expect(result.success).toBe(true);
    expect(result.path).toBeDefined();
    expect(fs.existsSync(result.path)).toBe(true);
  }, 30000); // Higher timeout for Puppeteer

  it('should fail if html_content is missing', async () => {
    const args = {
      filename: 'fail.pdf',
    };
    const result = await generatePDF(args);
    expect(result.success).toBe(false);
    expect(result.error).toContain('Contenuto HTML mancante');
  });

  afterAll(() => {
    if (fs.existsSync(testPath)) {
      fs.unlinkSync(testPath);
    }
  });
});
